# Generated by Django 3.0.3 on 2020-02-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Enter your email', max_length=100)),
                ('Location', models.CharField(blank=True, help_text='Enter your location', max_length=120)),
            ],
        ),
    ]
