# Generated by Django 3.0.3 on 2020-02-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='_UNK_', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(default='_UNK_', max_length=255),
        ),
    ]
