# Generated by Django 3.0.3 on 2020-02-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(help_text='Enter your location', max_length=254, unique=True),
        ),
    ]
