# Generated by Django 3.0.3 on 2020-02-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200217_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='location',
            field=models.ForeignKey(help_text='Enter your location', on_delete=django.db.models.deletion.PROTECT, to='signup.Location'),
        ),
    ]
